### ISSUE TITLE
Explaination for Vector Files

### ISSUE THREAD

**Issue by Manas-Embold** [bbowman410/VGraph#2]
Hi @bbowman410 

Few Quick Questions.

**Step 1:** Mine Patch and Vulnerable Source Code (.c/.cpp) and identified Vulnerable Function Names
**Question 1**: What is the logic to detect which functions names that were modified by a commit in a file.

**Step 2:** Mined Source Code of Patched and Vulnerable **functions** and generate CPG + Triplets for those CPG
**Question 2:** What i see from generated files, apart from CPG and Triplet there is also a .vec file , what is the use of .vec file what does it represent (Can't find reference of any vec file in paper).
In short i was expecting two files for each function i.e, ".gpickle" for CPG and ".triples" for triplets, but i see another file which is ".vec" file, what it is ?

**Step 3:** Convert Triplets to VGraph (Positive Triplet + Negative Triplet + Context Triplet.)
**Question 3**:  Again i was expecting three files to be generated for each functions, but i see total 6 files being generated for each function. What is the explanation / use of other three files in further steps of triplet matcher.
 "_pvg.pkl", "_nvg.pkl", "_cvg.pkl", "_p.pkl", "_v.pkl" and "_vec.pkl"
 
 I am going through code to understand the same, but i thought why not ask and clarify.
 
 Many Thanks

**Comment by bbowman410** [comment]
Q1:  When using git to diff files, it will print out the name of the functions and line numbers that have changed.  The function names are parsed out and then used to extract the specific functions of interest after Joern has generated the CPGs.

Q2: The .vec files are simple graph embeddings of the various CPGs.  They were left over from some experiments where I was trying to filter out some graphs so that I did not need to match all to all.  I didn't end up using them because the set-based matching was quick enough on it's own.

Q3: As mentioned previously the _vec.pkl is unused and was associated with a simple graph embedding for the vulnerable function.  _pvg,_nvg,and_cvg are positive triplets, negative triplets, and context triplets respectively.  And _p.pkl are triplets from the original patched function, and _v.pkl are triplets from the original vulnerable function.

**Comment by Manas-Embold** [comment]
Got it,
Thanks much.
