### ISSUE TITLE
Minor issue with calling "parsed_to_networkx.py" with "gen_target_graph_db.sh"

### ISSUE THREAD

**Issue by Manas-Embold** [bbowman410/VGraph#3]
Hi @bbowman410 

While generating target graph db for any c/cpp repo cloned from github, i get following error with line 49 "parsed_to_networkx.py"

Nodes: parsed_target/content/linux/mm/rmap.c/nodes.csv
Edges: parsed_target/content/linux/mm/rmap.c/edges.csv
Output: /content/VGraph/data/target_graph_db
Traceback (most recent call last):
  File "parsed_to_networkx.py", line 49, in <module>
    write_graph(g['graph'], output_dir + '/' + base_dir, g['name'])
TypeError: list indices must be integers or slices, not str

Any thoughts ?

**Comment by Manas-Embold** [comment]
'g' is supposed to be dictionary and not list , right ?

**Comment by Manas-Embold** [comment]
When i print a 'g' object here is what it looks

[{'location': '34:0:1208:1306', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71d1a90>, 'name': 'selinux_xfrm_enabled'}, {'location': '46:0:1655:1823', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71cf790>, 'name': 'selinux_xfrm_notify_policyload'}, {'location': '56:0:1831:1889', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71d4c50>, 'name': 'selinux_xfrm_enabled'}, {'location': '61:0:1892:2021', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71e5050>, 'name': 'selinux_xfrm_sock_rcv_skb'}, {'location': '67:0:2024:2178', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71e5790>, 'name': 'selinux_xfrm_postroute_last'}, {'location': '74:0:2181:2314', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a71852d0>, 'name': 'selinux_xfrm_decode_session'}, {'location': '81:0:2317:2375', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a7185310>, 'name': 'selinux_xfrm_notify_policyload'}, {'location': '85:0:2378:2482', 'graph': <networkx.classes.multidigraph.MultiDiGraph object at 0x7f20a7176b10>, 'name': 'selinux_xfrm_skb_sid'}]

**Comment by bbowman410** [comment]
Hmmm.. looks like I changed the joern_to_networkx() function to return a tuple (graphs, total_funcs_parsed)

Try changing the call in parsed_to_networkx.sh on line 47:

graphs = joern_to_networkx(parsed_nodes_file, parsed_edges_file)

 to

graphs, total_funcs_parsed = joern_to_networkx(parsed_nodes_file, parsed_edges_file)

**Comment by Manas-Embold** [comment]
That worked, Thanks Much
The work is awesome, however entire pipeline takes a lot of time.
Will see how to reduce time using tools like pydriller or using multiprocessing.

**Comment by Manas-Embold** [comment]
Hi @bbowman410 

I was trying to re create target db for another repositories.
I started with deleting
> rm -rf data/target_graph_db/
> rm -rf parsed_target/

Further when i run 
> bash gen_target_graph_db.sh 'PATH_TO_TARGET_CLONED_REPO'

The code gets stuck after a while (Tried multiple times for multiple target repositories)
here are last few logs:
Writing graph: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.gpickle
Writing triples: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.triples
Writing vector: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.vec

Any thoughts ?

Also, when i ran earlier, it appears to take a lot of time (Estimated time in progress bar 98 hours for small target repos) to run for approx hits (Is it usual ?)
> python3 find_vulns.py "data/target_graph_db" "stats_a.log" "hit_a.log" 'a'
![image](https://user-images.githubusercontent.com/61409155/107672834-5ffc8180-6cbb-11eb-9c6a-32d9d10cc70b.png)


For exact hits it runs pretty fast.

**Comment by Manas-Embold** [comment]
Is it something to do with the sleep 0.5 in gen_target_graph_db.sh ?
I tried removing it but that didn't helped.

`
    
    while [ "`jobs | wc -l`" -gt "$MAX_NUM_PROCS" ]; do
        sleep 0.5
    done

 `

**Comment by bbowman410** [comment]
Yeah so the approximate matching is again left-over from previous experiments.  In this case the 'approximate' is referring to the actual string-based characteristics of the triplets.  In other words it's looking at the actual source code contents and try to do approximate matching against those.  It takes way too long, which is why I moved away from it.  That's the primary reason for doing the abstraction from the source code to the node types.  This way, even though we are doing exact matching, there is some level of approximation because even if source code does not match exactly, node types have potential for matching.  I hope that makes sense.  In other words - I don't recommend using the string-based approximate matching.

**Comment by junkgear** [comment]
Thanks much.
Any thoughts on my first question ?
Why target db creation gets stuck indefinitely.

Repeating question again.

I was trying to re create target db for another repositories.
I started with deleting

rm -rf data/target_graph_db/
rm -rf parsed_target/

Further when i run

bash gen_target_graph_db.sh 'PATH_TO_TARGET_CLONED_REPO'

The code gets stuck after a while (Tried multiple times for multiple target repositories)
here are last few logs:
Writing graph: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.gpickle
Writing triples: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.triples
Writing vector: /vg/VGraph/data/target_graph_db/parsed_target/vg/scan/liboil/oil_resample.c//oil_fix_ratio.vec

Any thoughts ?

**Comment by bbowman410** [comment]
My guess is there is a particular function (or functions) that it's getting stuck on.  If you look in gen_target_graph_db.sh it's a very simple script that calls parsed_to_networkx.py for each file generated by Joern.  It runs the python calls in the background (via the '&' at end of line), and then waits in the loop with the sleep so that it doesn't add more processes than the MAX_NUM_PROCS.  I bet there is a file that is taking a long time to parse (perhaps it is very large, or was not parsed properly by Joern).

I would suggest running 'ps -ef | grep parsed_to_networkx' while the gen_target_graph_db.sh is stuck.  I bet you will see some functions that are still being parsed.  You could try to figure out why those functions are taking so long, or simply remove them for the time being.

Also, depending on how long you are waiting, it may just be a matter of just waiting longer for the particular functions to parse.

**Comment by junkgear** [comment]
Thank you once again for prompt response.
I would check back using  'ps -ef | grep parsed_to_networkx'  and get back.
